### ISSUE TITLE
BUG: `get_cool_off_threshold()` breaks in some cases after upgrading from 5.x to 8.x

### ISSUE THREAD

**Issue by romanek-adam-b2c2** [jazzband/django-axes#1424]
**Describe the bug**
`axes.attempts.get_cool_off_threshold` declares `request` as `Optional[HttpRequest]` (defaulting to `None`), but the function body unconditionally dereferences `request.axes_attempt_time`, causing an `AttributeError` whenever the function is called without a request — or with a request that has not gone through the axes failure-tracking path.

**To Reproduce**
Call `get_cool_off_threshold()` without arguments (as the function signature implies is valid):

```python
from axes.attempts import get_cool_off_threshold

threshold = get_cool_off_threshold()  # raises AttributeError
```

The above results in:
```
AttributeError: 'NoneType' object has no attribute 'axes_attempt_time'
  File "axes/attempts.py", line 23, in get_cool_off_threshold
    attempt_time = request.axes_attempt_time
```

Alternatively call `get_cool_off_threshold()` with a normal Django `HttpRequest` that was not produced by a failed login attempt (e.g. from inside a Django admin `get_queryset` override):

```python
def get_queryset(self, request):
    threshold = get_cool_off_threshold(request)  # raises AttributeError
```

**Expected behavior**
When `request` is `None`, or when `request` does not have `axes_attempt_time` set (i.e. is a normal request, not a failed-login request), the function should fall back to `now() - cool_off`, consistent with the intent of the `if attempt_time is None` branch already present in the code.

**Your environment**
python version: 3.13
django version: 5.2.12
django-axes 8.3.1 (after upgrading from 5.41.1)
Operating system: MacOS

**Additional context**
Line 23 in `axes/attempts.py` dereferences `request` unconditionally. The `# type: ignore[union-attr]` comment acknowledges this is unsafe, but the guard for `request is None` is missing entirely.

**Possible implementation**
```python
def get_cool_off_threshold(request: Optional[HttpRequest] = None) -> datetime:
    cool_off = get_cool_off(request)
    if cool_off is None:
        raise TypeError(
            "Cool off threshold can not be calculated with settings.AXES_COOLOFF_TIME set to None"
        )

    attempt_time = getattr(request, "axes_attempt_time", None)
    if attempt_time is None:
        return now() - cool_off
    return attempt_time - cool_off
```

Using `getattr` with a default of `None` handles both the `request=None` case and the case where the request exists but has not been through the axes failure handler.

**Comment by SparshGarg999** [comment]
Reproduced this locally. The issue is that `get_cool_off_threshold(request: Optional[HttpRequest] = None)` declares `request` as optional, but line 23 directly accesses `request.axes_attempt_time`:

```python
attempt_time = request.axes_attempt_time  # type: ignore[union-attr]
```

When `get_cool_off_threshold()` is called without arguments (`request=None`) or with a standard `HttpRequest` that does not have `axes_attempt_time` set, it raises an `AttributeError`.

Using `getattr(request, "axes_attempt_time", None)` safely returns `None` for both `request=None` and requests without the attribute, allowing the existing fallback `return now() - cool_off` to execute.

I will submit a PR with this fix and regression tests for `request=None` and unannotated requests.
